<?php # -*- coding: utf-8 -*-
// phpcs:disable

namespace Translationmanager\Tests\Unit\Inc\Functions;

use \Translationmanager\Tests\TestCase;

/**
 * Class VersionCompareTest
 *
 * @package Translationmanager\Tests\Unit\Inc\Functions
 */
class VersionCompareTest extends TestCase {

	/**
	 * Test Version Compare
	 *
	 * @dataProvider versionsProvider
	 */
	public function testVersionCompare( $ver1, $ver2, $constraint, $expected ) {

		$response = \Translationmanager\Functions\version_compare( $ver1, $ver2, $constraint );

		$this->assertSame(
			$expected,
			$response,
			'Ver1: ' . $ver1 . ' Ver2: ' . $ver2 . ' Constraint: ' . $constraint
		);
	}

	/**
	 * Data Provider for Versions
	 *
	 * @return array
	 */
	public function versionsProvider() {

		return [
			[ '1.0.0', '2.0.0', '>=', false ],
			[ '2.0.0', '2.0.0', '=', true ],
			[ '2.0.1', '2.0.0', '>=', true ],
			[ '3.0.0', '3.0.0-dev', '<=', true ],
			[ '3.0.0', '3.0.1-dev', '<=', true ],
			[ '3.5.0', '3.5.0-dev', '=', true ],
			[ '1.0.1-dev', '1.0.1-dev', '=', true ],
			[ '1.2.0-beta', '2.0.0', '<', true ],
			[ '3.0-dev', '2', '>', true ],
			[ '3-dev', '3', '=', true ],
		];
	}

	/**
	 * @inheritDoc
	 */
	protected function setUp() {

		require_once getenv( 'LIBRARY_PATH' ) . '/inc/functions/commons.php';

		parent::setUp(); // TODO: Change the autogenerated stub
	}
}
